### PR TITLE
Cleanup + Linux Support

### PR DESCRIPTION
**Pull request by happenpappen**
Hi Jean-Christophe,

i would like to contribute a Linux version and cleaned up the repository a little bit and made some code changes:

- Moved "SRC" to "src" (Linux filesystem is case-sensitive, so it's really annoying having upper case names)
- Removed the direcotries "v1.0.2" and "v1.0.3" - i would like to sugget to attach binary assets to releases, as this is a best practice.
- Added some changes to your code to make it support Linux (currently has a "works on my machine state" ;-)).

kind regards,

Christoph

### CODE REVIEW

**Comment by jczic** [comment]
Excellent @happenpappen 👍🏻 

I looked it up, it looks good indeed :)
Thank to you!

I'll update this as soon as, attach the binaries to the releases actually and change the readme for the download button links.
Do you think it's necessary to provide a binary version on Linux or users will know how to make it work very easily? :)

**Comment by jczic** [comment]
Merged! 👍🏻

**Comment by jczic** [comment]
Just @happenpappen, in "conf.py", are you sure that not call "expanduser()" on the path is always correct on Linux ?

``` python
Path('~/.config/')
```
or
``` python
Path('~/.config/').expanduser()
```

**Comment by happenpappen** [comment]
Yes, you're right the ".expanuser()" call is missing by accident and must be added. I'll create another PR for this.

**Pull request merged**
