### PR TITLE
Several Linux changes

### PR DESCRIPTION
**Pull request by happenpappen**
Updated Linux installation/build instructions in README.md and added a small script to create the binary. The Linux version will now search for "esptool" as well as for "esptool.py" when flashing the firmware.

### CODE REVIEW

**Comment by jczic** [comment]
Thank you very much @happenpappen !
It's really cool 👍🏻  :)
Just, in "create_binary.sh", it's necessarily for python 3.10 (hardcoded).

**Comment by happenpappen** [comment]
Yes, i'm not really happy with the hardcoded path and looking for a way to find this directory by other means.

**Comment by biemster** [comment]
`python -m site --user-site` doens't work?

**Comment by happenpappen** [comment]
@biemster : python -m site --user-site gives:

$HOME/.local/lib/python3.10/site-packages

but i need:

$VENVDIR/lib/python3.10/site-packages

in the script. Don't know if there is a python way to get this?

**Comment by biemster** [comment]
Hm, I was mistaken here indeed.. Then I don't really know any by heart, although a hacky one would of course be `$(python -m site | grep venv)`.

**Pull request merged**
